<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>VIP_L1_Loc 1314458807</name>
   <tag></tag>
   <elementGuidId>230fa6bd-1c53-4bf2-a047-7d2958725e7e</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>2addb185-5e87-44e1-8434-2ea23e2a7ef2</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.3.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>http://10.23.40.58:9068/get_next_best_offers?SUBSCRIBER_ID=${subs_id_changeLocation}&amp;CHANNEL_NAME=${chnl_nameOI}&amp;LOCATION=${loc_changeLocation}&amp;CGI_NAME=${cgi_1stLoc}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.subs_id_changeLocation</defaultValue>
      <description></description>
      <id>31740670-952c-4153-a18e-9db3649ff634</id>
      <masked>false</masked>
      <name>subs_id_changeLocation</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.chnl_nameOI</defaultValue>
      <description></description>
      <id>2b69c217-74e6-4c7a-8d93-da794252ecfc</id>
      <masked>false</masked>
      <name>chnl_nameOI</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.loc_changeLocation</defaultValue>
      <description></description>
      <id>64589a9f-5387-4ea0-81e8-a0c7d8560823</id>
      <masked>false</masked>
      <name>loc_changeLocation</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.cgi_1stLoc</defaultValue>
      <description></description>
      <id>936f7eae-b677-45a1-a7b5-e9391256fc44</id>
      <masked>false</masked>
      <name>cgi_1stLoc</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
