<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>VIP_Loc 1314458807</name>
   <tag></tag>
   <elementGuidId>39b034a6-4255-4395-9093-4986609a2b39</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>1ba5d32e-9047-44d4-b76e-3d081b202030</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.3.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>http://10.23.40.58:9068/get_next_best_offers?SUBSCRIBER_ID=${subs_id_changeLocation}&amp;CHANNEL_NAME=${chnl_nameOI}&amp;LOCATION=${loc_changeLocation}&amp;CGI_NAME=${cgi_changeLoc_L2}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.subs_id_changeLocation</defaultValue>
      <description></description>
      <id>cfaed2e0-ef78-4652-bd53-8e49559190dd</id>
      <masked>false</masked>
      <name>subs_id_changeLocation</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.chnl_nameOI</defaultValue>
      <description></description>
      <id>47a1e8d4-205e-4738-aed6-ba7c4b80dded</id>
      <masked>false</masked>
      <name>chnl_nameOI</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.loc_changeLocation</defaultValue>
      <description></description>
      <id>7c73e24a-50bc-4428-9ba4-14a192832919</id>
      <masked>false</masked>
      <name>loc_changeLocation</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.cgi_changeLoc_L2</defaultValue>
      <description></description>
      <id>bbecaeb4-75d9-4dc4-906f-5be6ca19ba6f</id>
      <masked>false</masked>
      <name>cgi_changeLoc_L2</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
