<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>VIP_L4_Loc 1314458807</name>
   <tag></tag>
   <elementGuidId>44fc32a8-a72d-4e62-b5d9-7f26ba114da4</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>7bf4815e-8e48-4baf-8424-d00e798b55cf</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.3.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>http://10.23.40.58:9068/get_next_best_offers?SUBSCRIBER_ID=${subs_id_changeLocation}&amp;CHANNEL_NAME=${chnl_nameOI}&amp;LOCATION=${loc_changeLocation}&amp;CGI_NAME=${cgi_changeLoc_L4}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.subs_id_changeLocation</defaultValue>
      <description></description>
      <id>6f7bf76e-eccb-45fa-98be-485e2229faa3</id>
      <masked>false</masked>
      <name>subs_id_changeLocation</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.chnl_nameOI</defaultValue>
      <description></description>
      <id>a731401e-4e69-4191-8548-e11447e79591</id>
      <masked>false</masked>
      <name>chnl_nameOI</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.loc_changeLocation</defaultValue>
      <description></description>
      <id>f7eb8008-35fa-4711-90ba-6f9f00a9840a</id>
      <masked>false</masked>
      <name>loc_changeLocation</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.cgi_changeLoc_L4</defaultValue>
      <description></description>
      <id>d0e18842-e0bd-42b0-b83c-5dcada8b8f19</id>
      <masked>false</masked>
      <name>cgi_changeLoc_L4</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
