<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>offerAccept</name>
   <tag></tag>
   <elementGuidId>44035c9a-f056-48ae-99cf-c6ded9d3f378</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>0ae7825f-0b52-47cf-a033-a1203727c6b5</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.3.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>http://10.23.40.58:9321/offer_accepted?SUBSCRIBER_ID=${subs_id_purchase}&amp;CHANNEL_NAME=${chnl_nameOI}&amp;LOCATION=${loc_purchase}&amp;OFFER_ID=${offerId}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.subs_id_purchase</defaultValue>
      <description></description>
      <id>0d0222d1-81ac-447d-b220-f76c8216e24d</id>
      <masked>false</masked>
      <name>subs_id_purchase</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.chnl_nameOI</defaultValue>
      <description></description>
      <id>11d97754-ab03-4355-8f96-d133824c698c</id>
      <masked>false</masked>
      <name>chnl_nameOI</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.loc_purchase</defaultValue>
      <description></description>
      <id>e9d104ad-111e-4d4e-923c-9fc823672efd</id>
      <masked>false</masked>
      <name>loc_purchase</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.offerId</defaultValue>
      <description></description>
      <id>4f89e8a3-ed69-4808-95ff-8cf7c4e88a01</id>
      <masked>false</masked>
      <name>offerId</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
