<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Validate KPI 594006887</name>
   <tag></tag>
   <elementGuidId>28293d9f-71b2-47f3-83c5-d1f50d41ed6a</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>9.3.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>http://10.24.164.46:46000/entities/mccm_subscriber_profile?entity_id=${subs_id_exactValue}&amp;subset_name=mccm_offer_drivers</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.subs_id_exactValue</defaultValue>
      <description></description>
      <id>8ceaacba-f270-4365-8e17-5b8fea0a11b4</id>
      <masked>false</masked>
      <name>subs_id_exactValue</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
